Repository SSAFY-79/algorithm-study, pull requests merged in 2022-02, with the labels that each got.

#5 최정인 / BOJ 5557, BOJ 14719 / DP, 구현 / 1주차
  src/algorithm/jungin/week1/boj/q14719/Main.java
  src/algorithm/jungin/week1/boj/q5557/Main.java
Labels: DP, 구현

#6 조민제 / BOJ 1913, BOJ 2578, BOJ 4396, BOJ 12933, BOJ 14467 / 구현 / 2주차
  src/algorithm/minje/week2/boj/q12933/Main.java
  src/algorithm/minje/week2/boj/q14467/Main.java
  src/algorithm/minje/week2/boj/q1913/Main.java
  src/algorithm/minje/week2/boj/q2578/Main.java
  src/algorithm/minje/week2/boj/q4396/Main.java
Labels: 구현

#7 이광우 / BOJ 1913, BOJ 2578, BOJ 4396, BOJ 12933, BOJ 14467 / 구현 / 2주차
  src/algorithm/kwangwoo/week1/boj/q14719/Main.java
  src/algorithm/kwangwoo/week1/boj/q5557/Main.java
  src/algorithm/kwangwoo/week2/boj/README.md
  src/algorithm/kwangwoo/week2/boj/q12933/Main.java
  src/algorithm/kwangwoo/week2/boj/q14467/Main.java
  src/algorithm/kwangwoo/week2/boj/q1913/Main.java
  src/algorithm/kwangwoo/week2/boj/q2578/Main.java
  src/algorithm/kwangwoo/week2/boj/q4396/Main.java
  src/algorithm/kwangwoo/week3/boj/README.md
  src/algorithm/kwangwoo/week3/boj/q17829/Main.java
  src/algorithm/kwangwoo/week3/boj/q20115/Main.java
  src/algorithm/kwangwoo/week3/boj/q20365/Main.java
  src/algorithm/kwangwoo/week3/boj/q2606/Main.java
  src/algorithm/kwangwoo/week3/boj/q9663/Main.java
Labels: 구현

#11 조민제 / BOJ 2606, BOJ 9663, BOJ 17829, BOJ 20115, BOJ 20365 / 그래프, 백트래킹, 분할 정복, 그리디 / 3주차
  src/algorithm/minje/week3/boj/q17829/Main.java
  src/algorithm/minje/week3/boj/q20115/Main.java
  src/algorithm/minje/week3/boj/q20365/Main.java
  src/algorithm/minje/week3/boj/q2606/Main.java
  src/algorithm/minje/week3/boj/q9663/Main.java
  src/algorithm/minje/week4/boj/Q11559/Main_11559_Puyo_Puyo_조민제.java
  src/algorithm/minje/week4/boj/Q1261/Main_1261_알고스팟_조민제.java
  src/algorithm/minje/week4/boj/Q16202/Main.java
  src/algorithm/minje/week4/boj/Q1701/Main_1701_Cubeditor_조민제.java
  src/algorithm/minje/week4/boj/Q1958/Main_1958_LCS_3_조민제.java
Labels: 그리디, 그래프, 백트래킹, 분할정복

#12 최정인 / BOJ 2606, BOJ 9663, BOJ 17829, BOJ 20115, BOJ 20365 / 그래프, 백트래킹, 분할 정복, 그리디 / 3주차
  src/algorithm/jungin/etc/q1094/Main.java
  src/algorithm/jungin/week3/boj/q17829/Main.java
  src/algorithm/jungin/week3/boj/q20115/Main.java
  src/algorithm/jungin/week3/boj/q20365/Main.java
  src/algorithm/jungin/week3/boj/q2606/Main.java
  src/algorithm/jungin/week3/boj/q9663/Main.java
  src/algorithm/jungin/week4/boj/q11559/Main.java
  src/algorithm/jungin/week4/boj/q1261/Main.java
  src/algorithm/jungin/week4/boj/q16202/Main.java
Labels: 그리디, 그래프, 백트래킹, 분할정복
